Maapilim
Bedu3/CH1Orange pull request #1
Opened 2018-09-06 03:46 UTC by victorurias1

2018-09-07 16:43 UTC, RodolfoSaldivar requested changes

2018-09-07 16:43 UTC, RodolfoSaldivar commented on app/css/maapilimv.css
> +body {
Hay que arreglar todo el css.
Tabular de manera ordenada y correcta y borrar las lineas vacias de hasta el final

2018-09-07 16:43 UTC, RodolfoSaldivar commented on app/html/indexv.html
> +          <div class="" ="use-image-container mobile-only">
error

2018-09-07 16:48 UTC, RodolfoSaldivar requested changes

2018-09-07 16:48 UTC, RodolfoSaldivar commented on app/html/indexv.html
> +<!DOCTYPE html>
No es responsivo y no debe de haber scroll horizontal

2018-09-09 04:32 UTC, RodolfoSaldivar approved these changes

2018-09-09 05:08 UTC, RZSTJP commented on app/css/maapilimv.css
> +  	background-color: #ca886e;
Corregir tabulacion

2018-09-09 05:09 UTC, RZSTJP commented on app/css/maapilimv.css
> +  	background-color: #e1d8c7;
Espacio de más

2018-09-09 05:10 UTC, jpglezco reviewed
Solo encontre dos propiedades que necesitan ser tabuladas.

2018-09-09 11:29 UTC, closed without merging