Juan
Bedu3/CH1Orange pull request #3
Opened 2018-09-08 08:20 UTC by RZSTJP

Pull request de mi sitio web.

2018-09-08 23:29 UTC, RodolfoSaldivar requested changes

2018-09-08 23:29 UTC, RodolfoSaldivar commented on app/html/indexj.html
> +                <img class=class="col-md-6" src="../img/cloud_section_bundle.svg" alt="" width="1000px">
esta imagen es la que se esta fregando todo lo responsivo y tiene un error porque se usa "class" de manera incorrecta

2018-09-09 03:59 UTC, RodolfoSaldivar approved these changes

2018-09-09 05:06 UTC, RZSTJP commented
Hola @RodolfoSaldivar @MatchaFierce @victorurias1, hice mi commit final del checkpoint. 

Estoy al pendiente en caso de ser necesario hacer correcciones o hacer merge a master.
Gracias!

2018-09-09 23:52 UTC, cesarvaldev approved these changes

2018-09-10 00:32 UTC, merged